alias matlablicstat="/apps/harris/license/bin/lmstat -c /apps/harris/license/MLM.lic -A | grep EDA_Simulator_Link -A 10"
alias create_subl_prj="source ~/.scripts/subl_vhdl_prj/create_subl_prj"
alias wget="wget --no-check-certificate"
# alias curl="curl --tlsv1.2"
alias create_git_repo="source ~/.scripts/create_git_repo"
